#!/usr/bin/env python3
"""Generate gen/file_ids.act and gen/file_registry.conf from the file registry.

Each non-comment registry line is:  <input|output>  <SYMBOL>  <path>

  * inputs  -> `pint <SYMBOL>` + a `name_table` entry
  * outputs -> `pint <SYMBOL>` + an `outname_table` entry

The symbol is used verbatim as the ACT constant name, so symbols must be
unique across *all* entries (an input and an output may not share one).
The pint value is the file's 0-based index within its kind, which is the
position actsim uses to look up the path in the corresponding string_table.
Paths are used verbatim (resolved relative to the current directory, which is
where the Makefile runs both this generator and actsim); input files must
already exist -- this script never creates or symlinks them.
"""
import re
import sys
from pathlib import Path

VALID_KINDS = ("input", "output")


def parse_registry(path):
    entries = []
    seen = set()

    for line_no, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue

        parts = line.split(None, 2)
        if len(parts) != 3:
            raise SystemExit(f"{path}:{line_no}: expected: <input|output> <SYMBOL> <path>")

        kind, symbol, filename = parts
        if kind not in VALID_KINDS:
            raise SystemExit(f"{path}:{line_no}: kind must be one of: {', '.join(VALID_KINDS)}")
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", symbol):
            raise SystemExit(f"{path}:{line_no}: symbol must look like MEM_IMAGE")
        if symbol in seen:
            raise SystemExit(f"{path}:{line_no}: duplicate symbol {symbol} (input and output symbols share one namespace)")

        seen.add(symbol)
        entries.append((kind, symbol, filename))

    return entries


def check_inputs_exist(entries):
    missing = [f for kind, _symbol, f in entries if kind == "input" and not Path(f).exists()]
    if missing:
        raise SystemExit(f"input file(s) not found: {', '.join(missing)}")


def paths_of(entries, kind):
    return [filename for k, _symbol, filename in entries if k == kind]


def act_lines(entries):
    counts = {"input": 0, "output": 0}
    lines = [
        "// Generated by tools/gen_file_registry.py from tests/files/file_registry.txt.",
        "// Edit the registry, then rerun the generator.",
        "",
    ]
    for kind, symbol, _filename in entries:
        lines.append(f"pint {symbol} = {counts[kind]};")
        counts[kind] += 1
    return lines


def quote(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def string_table(name, paths):
    return [f"    string_table {name} " + " ".join(quote(p) for p in paths)] if paths else []


def conf_lines(entries):
    return [
        "# Generated by tools/gen_file_registry.py from tests/files/file_registry.txt.",
        "# Edit the registry, then rerun the generator.",
        "begin sim",
        "begin file",
        *string_table("name_table", paths_of(entries, "input")),
        *string_table("outname_table", paths_of(entries, "output")),
        "end",
        "end",
    ]


def write_lines(path, lines):
    path.write_text("\n".join(lines) + "\n")


def main(argv):
    if len(argv) != 3:
        raise SystemExit("usage: gen_file_registry.py <registry.txt> <output-dir>")

    registry_path = Path(argv[1])
    output_dir = Path(argv[2])

    entries = parse_registry(registry_path)
    check_inputs_exist(entries)

    output_dir.mkdir(parents=True, exist_ok=True)
    write_lines(output_dir / "file_ids.act", act_lines(entries))
    write_lines(output_dir / "file_registry.conf", conf_lines(entries))


if __name__ == "__main__":
    main(sys.argv)
